baseurl: "/"
permalink: pretty
title: "OS Controls"
description: "OS Controls is about..."

collections_dir: collections
markdown: kramdown

collections:
  our-services:
    output: true
    permalink: /:collection/:path/
  cyber:
    output: true
    permalink: /:collection/:path/
  data-center:
    output: true
    permalink: /:collection/:path/
  process-control:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"
  - scope:
      type: cyber
    values:
      layout: cyber
      body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"
  - scope:
      type: data-center
    values:
      layout: datacenter
      body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"
  - scope:
      type: process-control
    values:
      layout: processcontrol
      body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

params:
  google_analytics_id: "G-WGCQTP3Y83"

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

paginate: 2
paginate_path: "/blog/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CREDITS.md
