baseurl: "/"
permalink: pretty
title: "OS Controls"
description: "OS Controls is about..."

collections_dir: collections
markdown: kramdown

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

collections:
  our-services:
    output: true
    permalink: /:collection/:path/
    layout: service
    body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"
  cyber:
    output: true
    permalink: /:collection/:path/
    layout: service
    body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"
  data-center:
    output: true
    permalink: /:collection/:path/
    layout: service
    body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"
  process-control:
    output: true
    permalink: /:collection/:path/
    layout: service
    body_classes: "page-template page-template-tpl_c_main_content page-template-tpl_c_main_content-php page page-id-186 page-parent page-child parent-pageid-10"

defaults:
  - scope:
      type: services
    values:
      layout: service
  - scope:
      type: cyber
    values:
      layout: service
  - scope:
      type: data-center
    values:
      layout: service
  - scope:
      type: process-control
    values:
      layout: service
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

params:
  google_analytics_id: "G-WGCQTP3Y83"

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

paginate: 2
paginate_path: "/blog/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CREDITS.md
