baseurl: '/'
permalink: pretty
title: 'OS Controls'

collections_dir: collections
markdown: kramdown

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

collections:
  capabilities:
    output: true
    permalink: /:collection/:path/
  industries:
    output: true
    permalink: /:collection/:path/
  culture:
    output: true
    permalink: /:collection/:path/
  insights:
    output: true
    permalink: /:collection/:path/
  about:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/
  work:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      type: capabilities
    values:
      layout: capabilities
  - scope:
      type: industries
    values:
      layout: industries
  - scope:
      type: insights
    values:
      layout: insights
  - scope:
      type: culture
    values:
      layout: culture
  - scope:
      type: about
    values:
      layout: about
  - scope:
      type: services
    values:
      layout: service
  - scope:
      type: work
    values:
      layout: work
  - scope:
      type: posts
    values:
      layout: post
      active: blog
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      path: 'pages'
    values:
      permalink: /:basename/

params:
  google_analytics_id: 'G-WGCQTP3Y83'
  global:
    header_fixed: true
  footer:
    show_menu_footer_primary: true
    show_menu_footer_secondary: true
    show_capabilities_links: true
    show_industries_links: true
    show_insights_links: true
    show_about_links: true
    show_services_links: false
    show_work_links: false
  homepage:
    show_services_section: true
    services_count: 6
    show_splash_section_one: true
    splash_one_link_url: work
    splash_one_link_text: Our Work
    splash_one_image: assets/images/hero/agile-leader-hero.jpg
    splash_one_heading: Deep Technology and Industry Experience
    splash_one_paragraph:
      Defions transforms the world’s most complex and critical enterprises through
      our deep technology and industry expertise. We improve the efficiency of
      digital channels between our customers and their end-users by minimizing
      technical complexities while adhering to user-centered design to make
      interactions intuitive and user-friendly.
    show_splash_section_two: true
    splash_two_link_url: work
    splash_two_link_text: Our Work
    splash_two_image: assets/images/hero/highly-regulated-hero.jpg
    splash_two_heading: Highly-Regulated Industries
    splash_two_paragraph:
      Defions specializes in simplifying digital channels and services for
      highly-regulated industries such as government, finance, and healthcare.
      We ensure the delivery of our services remain compliant for our customers
      within their respective sectors.
    show_splash_section_three: true
    splash_three_link_url: work
    splash_three_link_text: Our Work
    splash_three_image: assets/images/splash/splash-1.svg
    splash_three_heading: Transparent and Secure
    splash_three_paragraph:
      Defions shortens and continuously improves iterative feedback loops through
      its agile delivery-focused culture to dramatically increase transparency
      and observability for our customers. We include a team of experienced
      personnel who continuously review and mitigate all deliverables for
      any potential compliance and security vulnerabilities.
    show_splash_section_four: true
    splash_four_link_url: work
    splash_four_link_text: Our Work
    splash_four_image: assets/images/hero/agile-team-hero.jpg
    splash_four_heading: An Agile, Diverse, and Scalable Workforce
    splash_four_paragraph:
      Defions can scale the size of our delivery-focused teams to deliver
      customer-centric value singularly focused on mission accomplishment. We
      provide a customer-first culture with flexible ways of working,
      entrepreneurialism, and empowerment that enables us to collaborate
      seamlessly with customers.
    show_partners: true
    show_work_section: true
    work_section_heading: Our Work
    work_count: 2
    show_view_all_work_button: true
  homepage-footer:
    show_features: true
    show_splash_one_section: true
    splash_one_background_image: assets/images/hero/systems-integrator-hero.jpg
    splash_one_heading: We build great software
    splash_one_paragraph:
      Defions systematically rethinks how our customers can create value in their
      organizations and to their end-users through the use of digital channels
      and services.
  services:
    show_features: true
    show_splash_one_section: true
    splash_one_background_image: assets/images/hero/systems-integrator-hero.jpg
    splash_one_heading: We build great software
    splash_one_paragraph:
      Defions systematically rethinks how our customers can create value in their
      organizations and to their end-users through the use of digital channels
      and services.
  capabilities:
    show_features: true
    show_splash_one_section: true
    splash_one_background_image: assets/images/hero/systems-integrator-hero.jpg
    splash_one_heading: We build great software
    splash_one_paragraph:
      Defions systematically rethinks how our customers can create value in their
      organizations and to their end-users through the use of digital channels
      and services.
  industries:
    show_features: true
    show_splash_one_section: true
    splash_one_background_image: assets/images/hero/systems-integrator-hero.jpg
    splash_one_heading: We build great software
    splash_one_paragraph:
      Defions systematically rethinks how our customers can create value in their
      organizations and to their end-users through the use of digital channels
      and services.
  contact_cta:
    heading: Want to know more?
    subheading: Get in touch with us today.
    button_url: about/contact
    button_text: Learn More

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

paginate: 2
paginate_path: "/blog/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CREDITS.md
